exclude:
  - LICENSE.md
  - README.md
  - flake.lock
  - flake.nix
  - git-hooks.nix
  - treefmt.nix
highlighter: "rouge"
host: "0.0.0.0"
kramdown:
  gfm_emojis: true
  gfm_quirks:
    - "paragraph_end"
  input: "GFM"
markdown: "kramdown"
plugins:
  - "jekyll-seo-tag"
port: 8080
sass:
  style: "compressed"
site_title: "メカトロニクス研究部会"
social:
  links:
    - "https://github.com/mecha-natori"
    - "https://twitter.com/snct_lab"
  name: "メカトロニクス研究部会"
title: "メカトロニクス研究部会"
twitter:
  card: "summary"
  username: "snct_lab"
